title: helloWorld
author: gitlearnersurbhi
email: prasadsurbhi2001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Working on my first GitHub Page... just exploring and playing dude😉😜....finding it interesting

# social links
hankerank_username: prasadsurbhi2001@gmail.com
github_username:  gitlearnersurbhi # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
